
services:
  web:
    build:
      context: .
      args:
        - PROD=true
    ports:
      - "8000:8000"
    volumes:
      - ./devlab:/devlab 
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"